#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = []
# ///
"""SessionStart (startup|resume), cloud-only (cloud parity C1 + B2). No-op unless
CLAUDE_CODE_REMOTE=true. In a claude.ai cloud session it: (1) makes sure docker is up (spawns
dockerd, waits <= CS_DOCKER_WAIT s, default 30); (2) re-runs `npm ci` AND/OR `uv sync` (every
present lockfile) when sha256(package-lock.json + uv.lock, the present ones concatenated in that
order) differs from .claude/state/cloud-setup.stamp — an ABSENT stamp skips the re-sync with a note
(scripts/cloud-setup.sh owns the first install and writes the stamp); (3) `supabase start` when
supabase/config.toml exists; (4) writes .env.local + .env.test (mode 0600) from
`supabase status -o env` plus the `# cloud: env` keys of .env.example (never over a file lacking
the generated header); (5) seeds; (6) B2 drift — names the `# cloud: env` keys missing from the
environment. Every note goes out as ONE stdout systemMessage. Notes carry key names, step names
and exit statuses only — NEVER a value. A child that can't spawn fails only its own step
('not found' / 'timed out' / 'error <ERRNO>'). Fail-open: a crash prints a systemMessage and exits
0. Byte-parity Node twin: cloud_session.cjs."""
import errno
import hashlib
import json
import os
import re
import subprocess
import sys
import time

HEADER = "# generated by cloud_session — edits are overwritten"
ENV_KEY = re.compile(r"^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=.*#\s*cloud:\s*env\s*$")
LOCKS = (("package-lock.json", ["npm", "ci"]), ("uv.lock", ["uv", "sync"]))


def _err_name(e):
    """The errno name (EACCES, EISDIR, …) — what the Node twin's `e.code` prints — else the class."""
    return errno.errorcode.get(getattr(e, "errno", None) or -1) or type(e).__name__


def _run(argv, timeout, capture=False):
    """(status, stdout). status: 'ok' | 'not found' | 'timed out' | 'exit N' | 'error <ERRNO>'.
    Child output never reaches our stdout (it is the systemMessage channel, and may carry secrets)."""
    try:
        r = subprocess.run(argv, stdin=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
                           stdout=subprocess.PIPE if capture else subprocess.DEVNULL,
                           timeout=timeout, check=False)
    except FileNotFoundError:
        return "not found", ""
    except subprocess.TimeoutExpired:
        return "timed out", ""
    except OSError as e:
        return f"error {_err_name(e)}", ""
    out = r.stdout.decode("utf-8", "replace") if capture else ""
    return ("ok" if r.returncode == 0 else f"exit {r.returncode}"), out


def _docker(notes):
    if _run(["docker", "info"], 5)[0] == "ok":
        return True
    try:
        subprocess.Popen(["dockerd"], stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
                         stderr=subprocess.DEVNULL, start_new_session=True)
        for _ in range(int(os.environ.get("CS_DOCKER_WAIT", "30"))):
            time.sleep(1)
            if _run(["docker", "info"], 5)[0] == "ok":
                return True
    except OSError:
        pass  # dockerd missing / not spawnable → the note below
    notes.append("cloud_session: docker not running — supabase/e2e unavailable")
    return False


def _resync(root, notes):
    present = [(os.path.join(root, lock), argv) for lock, argv in LOCKS
               if os.path.isfile(os.path.join(root, lock))]
    if not present:
        return
    stamp = os.path.join(root, ".claude", "state", "cloud-setup.stamp")
    if not os.path.isfile(stamp):
        notes.append("cloud_session: no cloud-setup.stamp — dependencies not re-synced; run "
                     "scripts/cloud-setup.sh (the claude.ai environment setup script) once")
        return
    h = hashlib.sha256()
    for path, _ in present:
        with open(path, "rb") as f:
            h.update(f.read())
    digest = h.hexdigest()
    with open(stamp, encoding="utf-8") as f:
        if f.read().strip() == digest:
            return
    all_ok = True
    for _, argv in present:
        status = _run(argv, 300)[0]
        notes.append(f"cloud_session: lockfile changed — {' '.join(argv)} {status}")
        all_ok = all_ok and status == "ok"
    if all_ok:
        with open(stamp, "w", encoding="utf-8") as f:
            f.write(digest + "\n")


def _env_keys(root):
    path = os.path.join(root, ".env.example")
    if not os.path.exists(path):
        return []
    with open(path, encoding="utf-8") as f:
        return [m.group(1) for m in map(ENV_KEY.match, f.read().splitlines()) if m]


def _env(k):
    """KEY's value, else CLOUD_<KEY>'s: claude.ai drops reserved names (ANTHROPIC_API_KEY) from the
    session environment, so those are stored in the cloud env under a CLOUD_ prefix."""
    return os.environ.get(k) or os.environ.get("CLOUD_" + k)


def _write_env_files(root, stack_lines, keys, notes):
    # ponytail: raw KEY=value — a multi-line value would need dotenv quoting; add it when one appears.
    lines = stack_lines + [f"{k}={_env(k)}" for k in keys if _env(k)]
    if not lines:
        return
    body = ("\n".join([HEADER, *lines]) + "\n").encode("utf-8")
    for name in (".env.local", ".env.test"):
        path = os.path.join(root, name)
        if os.path.exists(path):
            with open(path, encoding="utf-8") as f:
                if f.readline().rstrip("\n") != HEADER:
                    notes.append(f"cloud_session: kept hand-edited {name}")
                    continue
        fd = os.open(path, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
        try:
            os.fchmod(fd, 0o600)  # owner-only even when rewriting a pre-existing 0644 file
            os.write(fd, body)
        finally:
            os.close(fd)


def _seed(root, notes):
    try:
        with open(os.path.join(root, "package.json"), encoding="utf-8") as f:
            has_script = "seed:test" in (json.load(f).get("scripts") or {})
    except (OSError, ValueError, AttributeError):
        has_script = False
    if has_script:
        notes.append(f"cloud_session: seed: npm run seed:test {_run(['npm', 'run', 'seed:test'], 300)[0]}")
    elif os.path.isfile(os.path.join(root, "supabase", "seed.sql")):
        notes.append("cloud_session: seed: supabase/seed.sql (applied by supabase start)")
    else:
        notes.append("cloud_session: seed: none found")


def _env_name(root):
    try:
        with open(os.path.join(root, ".claude", "worktrees.conf"), encoding="utf-8") as f:
            for line in f:
                if line.startswith("CLOUD_ENV_NAME="):
                    val = line.split("=", 1)[1]
                    val = re.sub(r"\s+#.*$", "", val)  # strip a trailing ` # comment`
                    return val.strip().strip("\"'")
    except OSError:
        pass
    return os.path.basename(os.path.abspath(root)) + "-dev"


def run(root):
    notes = []
    docker_up = _docker(notes)
    _resync(root, notes)
    stack_lines = []
    if os.path.isfile(os.path.join(root, "supabase", "config.toml")) and docker_up:
        status = _run(["supabase", "start"], 240)[0]
        if status == "ok":
            status, out = _run(["supabase", "status", "-o", "env"], 30, capture=True)
            stack_lines = [ln for ln in out.splitlines() if re.match(r"^[A-Za-z_][A-Za-z0-9_]*=", ln)]
        if status != "ok":
            notes.append(f"cloud_session: supabase {status}")
    keys = _env_keys(root)
    _write_env_files(root, stack_lines, keys, notes)
    _seed(root, notes)
    missing = [k for k in keys if not _env(k)]
    if missing:
        notes.append(f"cloud_session: cloud env {_env_name(root)} is missing: {', '.join(missing)}")
    return notes


def main():
    if os.environ.get("CLAUDE_CODE_REMOTE") != "true":
        return
    try:
        notes = run(os.environ.get("CLAUDE_PROJECT_DIR") or os.getcwd())
    except Exception as e:  # noqa: BLE001 — fail open, but visibly
        notes = [f"cloud_session: crashed ({_err_name(e)}) — cloud bootstrap skipped"]
    if notes:
        text = "\n".join(notes)
        # systemMessage reaches the user only; additionalContext tells the model too (T12 canary).
        msg = json.dumps({"systemMessage": text, "hookSpecificOutput": {
            "hookEventName": "SessionStart", "additionalContext": text}},
            ensure_ascii=False, separators=(",", ":"))
        sys.stdout.buffer.write((msg + "\n").encode("utf-8"))


if __name__ == "__main__":
    main()
