"""Block an Edit/Write/NotebookEdit targeting a disposable plugin-cache copy (plugin-cache guard)."""

import os

from _lib.shell import _process_env_override


def _plugin_cache_block(file_path: str, project_dir: str):
    """BLOCK an in-place edit of a file under the machine-global plugin cache
    (~/.claude/plugins/{cache,marketplaces}/...). Such a copy is regenerated by `claude plugin
    update`, shared by every repo, and an edit there never propagates and is silently dropped on the
    next version switch. Match the REQUESTED expanded path (not realpath) so a repo-side dev-link
    stays editable. Fail-open on anything unexpected. Bypass: CT_ALLOW_PLUGIN_EDIT=1."""
    if not file_path or _process_env_override("CT_ALLOW_PLUGIN_EDIT"):
        return
    try:
        p = os.path.expanduser(file_path)
        abs_path = p if os.path.isabs(p) else os.path.join(project_dir or ".", p)
        abs_path = os.path.abspath(abs_path)
    except Exception:  # noqa: BLE001 - never brick a session on a bad path
        return
    # normpath the home too: abs_path is already abspath-normalized, so an un-normalized HOME
    # (a trailing or doubled slash — e.g. TMPDIR="/tmp/") would break the prefix match otherwise.
    home = os.path.normpath(os.path.expanduser("~"))
    cache_root = os.path.join(home, ".claude", "plugins", "cache") + os.sep
    mkt_root = os.path.join(home, ".claude", "plugins", "marketplaces") + os.sep
    if abs_path.startswith(cache_root):
        parts = abs_path[len(cache_root):].split(os.sep)
        # cache/<marketplace>/<plugin>/<version>/<relpath...> -> plugins/<plugin>/<relpath...>
        if len(parts) > 3:
            upstream = "plugins/" + parts[1] + "/" + "/".join(parts[3:])
        else:
            upstream = "the plugin's source"
    elif abs_path.startswith(mkt_root):
        upstream = "the plugin's own source repo"
    else:
        return
    return (
        f"Blocked: {abs_path} is a regenerated plugin-cache copy (machine-global, overwritten by "
        "`claude plugin update`; an edit here never reaches other repos and is silently dropped on the "
        f"next update). Edit the source upstream instead — for claude-template that is {upstream} in your "
        "claude_template checkout. Override just this edit with CT_ALLOW_PLUGIN_EDIT=1."
    )


def check(ctx):
    # NotebookEdit's payload names the path `notebook_path`, not `file_path` — fall back so the
    # NotebookEdit wiring actually blocks a real notebook edit, not just a `file_path`-shaped one.
    ti = ctx.tool_input
    return _plugin_cache_block(ti.get("file_path") or ti.get("notebook_path") or "", ctx.project_dir)
